### ISSUE TITLE
Failing to compile sapp-linux

### ISSUE THREAD

**Issue by Bombfuse** [not-fl3/miniquad#85]
It looks like [this line](https://github.com/not-fl3/miniquad/blob/master/native/sapp-linux/src/lib.rs#L1132) is failing to compile.

Tried compiling from a Raspberry Pi 3
Tried Cross-compiling on WSL/Ubuntu targeting arm7-unknown-linux-gnueabihf

```error[E0308]: mismatched types
    --> /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/sapp-linux-0.1.7/src/lib.rs:1132:46
     |
1132 |             let rust_msg = CString::from_raw(msg as *mut i8);
     |                                              ^^^^^^^^^^^^^^ expected `u8`, found `i8`
     |
     = note: expected raw pointer `*mut u8`
                found raw pointer `*mut i8`

error: aborting due to previous error
```

**Comment by not-fl3** [comment]
Fixed that specific error and now it builds for arm-unknown-linux-gnueabihf

But I am not sure that miniquad will works on raspberry - afaik there was some raspberry-specific GL loader required.

**Comment by Bombfuse** [comment]
I'm targeting the Gameshell which is some flavor of some linux distro. Also not sure if it will run but I'll try it out!

**Comment by Bombfuse** [comment]
I'm sourcing from the repo/master but I'm still getting the same error as before even after ```cargo update```.

I'm curious if instead of "_", it explicitly has to be "u8". I'll clone and try it out

**Comment by Bombfuse** [comment]
Can confirm that changing it to a ```u8``` fixes the problem! It now runs on raspberry pi! Next, to try the gameshell

**Comment by not-fl3** [comment]
Hm, interesting, `_` works for me with `cargo build --arm-unknown-linux-gnueabihf` and I can't see the difference with `_` and `u8`. 
How do you compile for raspberry? Any way to reproduce this error?

**Comment by Bombfuse** [comment]
Just a regular ```cargo build``` on the pi works when the u8 change. Not sure how to reproduce it without using Raspbian, maybe it's possible to spin it up in a VM.

**Comment by not-fl3** [comment]
Just tried on the raspbian and it works for me. (just for the record - miniquad took 13 minutes to compile in qemu and raspbian). 
Could you try it again and post an error? I guess something is wrong with cargo versions, caches or something like that.

I found the source of the problem: https://github.com/rust-lang/rust/issues/29867 and very similar fix: https://github.com/alacritty/alacritty/pull/60/files

**Comment by Bombfuse** [comment]
Yah I can try it out again tonight and get some more details

**Comment by not-fl3** [comment]
awesome, thanks!

**Comment by Bombfuse** [comment]
Yah it looks like it was ultimately the quad-gl dependency I had that was erroring out, because it didn't have the updated code. I removed the dependency and it builds properly now! Looks like its fixed

**Comment by not-fl3** [comment]
Awesome! 
This means that RPI-3+ is now supported by miniquad! :tada: 
Will keep it open - because of RPI-2 with opengl 2.

**Comment by Bombfuse** [comment]
I haven't ran it on the actual Pi yet, just cross-compiled from WSL/Ubuntu. I can try to get a window open on the Pi to confirm though!

**Comment by Bombfuse** [comment]
Can confirm it runs on raspberry pi!

**Comment by Bombfuse** [comment]
Appears that there's a new break in sapp-linux

`cargo build --example bunnymark --release --target armv7-unknown-linux-gnueabihf`

```macbook:emerald bombfuse$ cargo build --example bunnymark --release --target armv7-unknown-linux-gnueabihf
warning: unused manifest key: target.armv7-unknown-linux-gnueabihf.linker
   Compiling sapp-linux v0.1.8 (https://github.com/not-fl3/miniquad#85e3fe5e)
   Compiling crossbeam-queue v0.2.3
   Compiling crossbeam-channel v0.4.2
   Compiling rand_core v0.5.1
   Compiling crossbeam-epoch v0.8.2
   Compiling indexmap v1.5.0
error[E0308]: mismatched types
    --> /Users/bombfuse/.cargo/git/checkouts/miniquad-e9b2a2fb4d6640d7/85e3fe5/native/sapp-linux/src/lib.rs:1277:42
     |
1277 |             data: ClientMessageData { l: data },
     |                                          ^^^^ expected `i32`, found `i64`
     |
     = note: expected array `[i32; 5]`
                found array `[i64; 5]`

   Compiling fontdue v0.1.2 (https://github.com/mooman219/fontdue#f9862e34)
error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `sapp-linux`.
```

**Comment by iamwacko** [comment]
RPI-3+ builds are broken. I get mismatched type errors `expected 'u8', found 'i8'` all over the code.

**Comment by not-fl3** [comment]
> RPI-3+ builds are broken. I get mismatched type errors `expected 'u8', found 'i8'` all over the code.

Thanks for the report! Totally overlooked an RPI in the 0.3 update PR, we should definitely add it to the CI somehow! 

Can't promise a fix soon, making an RPI setup will take some time, not sure I'll have time for this super soon :(

PRs very welcome tho!
